CREATE SCHEMA weather_project;

USE weather_project ;

CREATE TABLE LOCATION(LOCATION_ID INT ,CITY VARCHAR(40) NOT NULL , STATE VARCHAR(40) ,PRIMARY KEY(LOCATION_ID));

CREATE TABLE NEIGHBOURHOOD(NEIGHBOURHOOD_ID INT,NEIGHBOURHOOD_NAME VARCHAR(40) NOT NULL,LOCATION_ID INT,PRIMARY KEY(NEIGHBOURHOOD_ID),FOREIGN KEY(LOCATION_ID) REFERENCES LOCATION(LOCATION_ID) ON DELETE CASCADE ON UPDATE CASCADE);

CREATE TABLE METEROLOGICAL_STATIONS(STATION_ID INT PRIMARY KEY ,STATION_NAME VARCHAR(40) NOT NULL,STATION_TYPE VARCHAR(40) NOT NULL,NEIGHBOURHOOD_ID INT ,FOREIGN KEY(NEIGHBOURHOOD_ID) REFERENCES NEIGHBOURHOOD(NEIGHBOURHOOD_ID) ON DELETE CASCADE ON UPDATE CASCADE );

CREATE TABLE WEATHER_OBSERVATIONS(WEATHER_OBS_ID INT PRIMARY KEY ,OBS_TIME time NOT NULL,OBS_DATE date NOT NULL,STATION_ID INT ,TEMPERATURE DOUBLE NOT NULL ,CLOUD_COVERAGE  FLOAT ,FOREIGN KEY (STATION_ID) REFERENCES METEROLOGICAL_STATIONS(STATION_ID) ON DELETE CASCADE ON UPDATE CASCADE);

CREATE TABLE HAS_EVENTS(EVENT_ID INT PRIMARY KEY ,EVENT_NAME VARCHAR(40) NOT NULL);

CREATE TABLE OBS_PRECIPITATION(WEATHER_OBS_ID INT ,EVENT_ID INT,PRECIPITATION FLOAT NOT NULL,PRIMARY KEY(WEATHER_OBS_ID,EVENT_ID),FOREIGN  KEY(WEATHER_OBS_ID) REFERENCES WEATHER_OBSERVATIONS(WEATHER_OBS_ID)ON DELETE CASCADE ON UPDATE CASCADE,FOREIGN KEY(EVENT_ID) REFERENCES HAS_EVENTS(EVENT_ID) ON DELETE CASCADE ON UPDATE CASCADE);